In [5]:
import numpy as np

In [6]:
arr1 = np.array([12, 23, 45, 67, 89])

In [8]:
arr1

array([12, 23, 45, 67, 89])

In [17]:
arr=([12, 32.86, 'Harshada']) #datatype - unicode string of length is less than 32 dtype='<U32'

In [23]:
%%timeit
arr2 = np.array([23, 34, 54, 12.34, 'Harshada'])

7.62 µs ± 329 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [19]:
arr1.dtype

dtype('int32')

In [26]:
arr1.shape

(5,)

In [27]:
arr1

array([12, 23, 45, 67, 89])

In [28]:
arr1 + 10

array([22, 33, 55, 77, 99])

In [29]:
arr1[1]

23

# linear Equation

In [30]:
x = np.array([23, 67, 34, 21, 89])

In [32]:
new1 = x + 3.4 + 12
new1

array([ 38.4,  82.4,  49.4,  36.4, 104.4])

In [33]:
y = np.arange(10)
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
y = np.arange(2, 10)
y

array([2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
y = np.arange(100, 1000)
y

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
       152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
       165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
       178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190,
       191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203,
       204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216,
       217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229,
       230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242,
       243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255,
       256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268,
       269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 28

In [37]:
np.arange(5, 25, 0.5)

array([ 5. ,  5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ,
       10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5,
       16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5, 21. ,
       21.5, 22. , 22.5, 23. , 23.5, 24. , 24.5])

In [39]:
np.arange(-5, 5, 0.5)

array([-5. , -4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,
        0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [40]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [41]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [42]:
arr2d = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9], [10, 11, 12]])
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [43]:
arr2d.ndim

2

In [44]:
arr2d.shape

(4, 3)

In [45]:
type(arr2d)

numpy.ndarray

In [46]:
arr2d.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [47]:
arr2d.flatten().shape

(12,)

In [48]:
arr2d.size

12

In [51]:
arr2d.reshape(3, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [52]:
arr2d.reshape(6, 2) #2dimensional

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [53]:
arr2d.reshape(6, -1)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [54]:
arr2d.reshape(-1, 2) #not know about the row

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [59]:
arr2d.reshape(3, 2, 2) #3dimensional

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [60]:
arr2d.ndim

2

In [76]:
arr2d = np.array([[[1, 2, 3], [4, 5, 6],[7, 8, 9], [10, 11, 12]]])
arr2d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [79]:
arr2d = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9], [10, 11, 12]])
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [80]:
arr2d[0:3, 0:2] #slicing

array([[1, 2],
       [4, 5],
       [7, 8]])

In [81]:
arr2d[0:, 0:2]

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

In [87]:
arr2d[1, 1]

5

In [88]:
arr2d[1:2, 1:2]

array([[5]])

In [93]:
arr = np.array([2, 4, 5, 7, 2, 2, 8, 5, -1])

In [90]:
np.unique(arr)

array([2, 4, 5, 7, 8])

In [91]:
np.mean(arr)

4.375

In [92]:
np.max(arr)

8

In [94]:
np.abs(arr) #convert negative value to positive values

array([2, 4, 5, 7, 2, 2, 8, 5, 1])

In [ ]:
np.